### ISSUE TITLE
For ReCaptcha enterprise enabled sign in forms automation tests are passing

### ISSUE THREAD

**Issue by utsavbshah** [googleapis/nodejs-recaptcha-enterprise#307] opened 2021-08-13 14:22 UTC
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
 - The client library.

2) Did someone already solve this?
  - Not able to find.

3) Do you have a support contract?
- No

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: Windows 10
  - Node.js version: 14.17.5
  - npm version: 6.14.5
  - `@google-cloud/recaptcha-enterprise` version: 2.1.6

#### Steps to reproduce

  1. Create a simple sign-in form with an enterprise ReCaptcha script.
  2. Run automation tests for that form.

- Tests should fail with ReCaptcha verification fail but the same tests are passing with token properties 
```
tokenProperties: {
      valid: true,
      invalidReason: 'INVALID_REASON_UNSPECIFIED',
      createTime: [Object],
      hostname: <my_host>,
      action: 'my_action'
    }
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by bcoe** [comment] 2021-08-13 16:32
@utsavbshah I'm wondering, is this a duplicate of #308?

I think it would be worth sending feedback [here](https://cloud.google.com/recaptcha-enterprise/docs/overview), to the product team.

**Closed** 2022-11-11 01:02 UTC
Labels: priority: p2, type: bug, external, api: recaptchaenterprise
